modLoader="javafml"
loaderVersion="[31,)" 
issueTrackerURL="https://github.com/TeamFelnull/IamMusicPlayer/issues"
[[mods]]
modId="iammusicplayer"
version="${file.jarVersion}" 
displayName="Iam Music Player"
updateJSONURL="https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/version_check.json" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/iammusicplayer" 
logoFile="null.png" 
credits="nin8995,MultiGamer8853,toranpfan6433,TeamFelNull"
authors="MORIMORI0317" 
description="Thank you for downloading!\nThis mod is add Ikisugi Music player."
